In [1]:
import numpy as np

In [2]:
def create_processes(n = 0):
    processes = np.random.randint(low = 1, high = 6, size = n)
    querry = np.zeros((n,0))
    return processes,querry

In [3]:
def compute_fcfs(processes, querry):
    n = len(processes)
    for i in range(n):
        for j in range(processes[i]):
            array = np.array([[0]*(i)+[1]+[-1]*(n-i-1)]).transpose()
            querry = np.append(querry, array, axis=1)
    return querry

In [4]:
def compute_sjf(processes, querry):
    n = len(processes)
    t = list(processes)
    t.sort()
    for i in range(n):
        for j in range(t[i]):
            array = np.array([[0]*(i)+[1]+[-1]*(n-i-1)]).transpose()
            querry = np.append(querry, array, axis=1)
    return querry

In [5]:
process , gantt_f = create_processes(n = 5)

In [6]:
process

array([3, 2, 2, 1, 2])

In [7]:
gantt = compute_fcfs(process, gantt_f)

In [8]:
gantt

array([[ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1.,  1.,  1.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1.,  1.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.]])

In [9]:
gantt1 = compute_sjf(process, gantt_f)
gantt1

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1.,  1.,  1.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.]])

In [10]:
def count_downtime(array):
    unique, counts = np.unique(array, return_counts=True)
    d = dict(zip(unique, counts))
    print("Среднее время ожидания", d[-1]/5)
def count_working(array):
    unique, counts = np.unique(array, return_counts=True)
    d = dict(zip(unique, counts))
    print("Среднее время выполнения", (d[-1] + d[1])/5)

In [11]:
count_downtime(gantt)
count_working(gantt)

Среднее время ожидания 4.6
Среднее время выполнения 6.6


In [12]:
count_downtime(gantt1)
count_working(gantt1)

Среднее время ожидания 3.2
Среднее время выполнения 5.2


In [13]:
gantt

array([[ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1.,  1.,  1.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1.,  1.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.]])

In [14]:
gantt1

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1.,  1.,  1.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.]])